"use strict";

exports.menulist = [
// {
//     "createDate": 1637548754623,
//     "creator": 1,
//     "frontendId": 1,
//     "icon": "system",
//     "menuIndex": 0,
//     "menuName": "系统设置",
//     "menuStatus": 1,
//     "parentId": 0,
//     "reserveStatus": 1,
//     "updateTime": 1637207660972,
//     "updateor": 1,
//     "urlPath": "/system",
//     "children": [{
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 3,
//         "icon": "",
//         "menuIndex": 0,
//         "menuName": "用户管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/user"
//     }, {
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 17,
//         "icon": "setting",
//         "menuIndex": 0,
//         "menuName": "日志管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/log"
//     }, {
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 16,
//         "icon": "setting",
//         "menuIndex": 0,
//         "menuName": "权限管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/jurisdiction"
//     }, {
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 15,
//         "icon": "setting",
//         "menuIndex": 0,
//         "menuName": "菜单管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/menu"
//     }, {
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 14,
//         "icon": "setting",
//         "menuIndex": 0,
//         "menuName": "部门管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/department"
//     }, {
//         "children": [],
//         "createDate": 1637548754623,
//         "creator": null,
//         "frontendId": 4,
//         "icon": "el-icon-user",
//         "menuIndex": 0,
//         "menuName": "角色管理",
//         "menuStatus": 1,
//         "parentId": 1,
//         "reserveStatus": 1,
//         "updateTime": 0,
//         "updateor": null,
//         "urlPath": "/role"
//     }]
// },
{
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 0,
  "icon": "system",
  "menuIndex": 0,
  "menuName": "主页",
  "menuStatus": 111,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/home/index",
  "children": []
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 0,
  "icon": "system",
  "menuIndex": 0,
  "menuName": "任务详情",
  "menuStatus": 111,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/task/index",
  "children": []
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 10,
  "icon": "wenzishibie",
  "menuIndex": 1,
  "menuName": "文字识别",
  "menuStatus": 1,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/wenzishibie",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 11,
    "icon": "",
    "menuIndex": 0,
    "menuName": "通用文字识别",
    "menuStatus": 1,
    "parentId": 10,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/tongyongwenzishibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 12,
    "icon": "",
    "menuIndex": 0,
    "menuName": "卡证文字识别",
    "menuStatus": 1,
    "parentId": 10,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/kazhengwenzishibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 13,
    "icon": "",
    "menuIndex": 0,
    "menuName": "票据单据识别",
    "menuStatus": 1,
    "parentId": 10,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/piaojudanjushibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 14,
    "icon": "",
    "menuIndex": 0,
    "menuName": "汽车证件识别",
    "menuStatus": 1,
    "parentId": 10,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/qichezhengjianshibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 15,
    "icon": "",
    "menuIndex": 0,
    "menuName": "智能扫码",
    "menuStatus": 1,
    "parentId": 10,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/zhinengsaoma"
  }]
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 20,
  "icon": "renlianshibie",
  "menuIndex": 2,
  "menuName": "人脸识别",
  "menuStatus": 1,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/renlianshibie",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 21,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人物资料录入",
    "menuStatus": 1,
    "parentId": 20,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renwuziliaoluru"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 22,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人物身份识别",
    "menuStatus": 1,
    "parentId": 20,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renwushenfenshibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 23,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人脸识别",
    "menuStatus": 1,
    "parentId": 20,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renlianshibie"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 24,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人脸对比",
    "menuStatus": 1,
    "parentId": 20,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renlianduibi"
  }]
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 30,
  "icon": "renliantexiao",
  "menuIndex": 3,
  "menuName": "人脸特效",
  "menuStatus": 1,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/renliantexiao",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 31,
    "icon": "",
    "menuIndex": 0,
    "menuName": "智能美肤",
    "menuStatus": 1,
    "parentId": 30,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/zhinengmeifu"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 32,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人像变换",
    "menuStatus": 1,
    "parentId": 30,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renxiangbianhuan"
  }]
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 40,
  "icon": "rentishibie",
  "menuIndex": 4,
  "menuName": "人体识别",
  "menuStatus": 1,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/rentishibie",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 41,
    "icon": "",
    "menuIndex": 0,
    "menuName": "人像分割",
    "menuStatus": 1,
    "parentId": 40,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/renxiangfenge"
  }, {
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 42,
    "icon": "",
    "menuIndex": 0,
    "menuName": "图像超放",
    "menuStatus": 1,
    "parentId": 40,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/tuxiangchaofang"
  }]
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 50,
  "icon": "yuyinshibie",
  "menuIndex": 5,
  "menuName": "语音识别",
  "menuStatus": 1,
  "parentId": 0,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/yuyinshibie",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 51,
    "icon": "",
    "menuIndex": 0,
    "menuName": "语音识别",
    "menuStatus": 1,
    "parentId": 50,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/yuyinshibie"
  }]
}, {
  "createDate": 1637548754623,
  "creator": 1,
  "frontendId": 60,
  "icon": "ziranyuyan",
  "menuIndex": 6,
  "menuName": "自然语言",
  "menuStatus": 1,
  "parentId": 50,
  "reserveStatus": 1,
  "updateTime": 1637207660972,
  "updateor": 1,
  "urlPath": "/ziranyuyan",
  "children": [{
    "children": [],
    "createDate": 1637548754623,
    "creator": null,
    "frontendId": 61,
    "icon": "",
    "menuIndex": 0,
    "menuName": "词法分析",
    "menuStatus": 1,
    "parentId": 60,
    "reserveStatus": 1,
    "updateTime": 0,
    "updateor": null,
    "urlPath": "/cifafenxi"
  }]
}];